### ISSUE TITLE
Autocompletion interaction with arrows

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/vitrivr-ui#10]
When you are given a list of possible labels, pressing arrow keys should move the selected label (the one which gets added when pressing ENTER) down or up. Currently the only way to  select a label which is not at the top is by clicking on it.

**Comment by christianfrei** [comment]
Isn't at the moment possible even with the example from materialize on their homepage. After the demo I will change the auto completion I found several approaches for this problem. This could possibly fix also the bug in #9 .

**Comment by christianfrei** [comment]
New version of autocompletion implemented. 

Navigation with arrow keys is now possible. Tags can be added either with Enter when marked in dropdown or by clicking on it. No additional "add" button have to be clicked in this version. With pressing enter or clicking on a tag will automatically be added to concepts-array.

Added tags will be displayed beloved the autocompletion input with "chips".

Deleting tags can either be achieved by clicking on the delete button at the right of the chips or by pressing backspace (last one added will be deleted first).

Needs testing if concepts are sended correctly to cineast. 

0a2fcb8fbaa4ade070b5fd087ecec41edce942bb

**Comment by christianfrei** [comment]
By hitting Enter the first entry of the select should be added.

**Comment by lucaro** [comment]
Why is this labeled as 'wontfix', as far as I understand, this is already implemented..?

**Comment by silvanheller** [comment]
Closing issue
