### ISSUE TITLE
Pull Request check of NN is working 

### ISSUE THREAD

**Issue by christianfrei** [silvanheller/vitrivr-ui#19]
After pull request it has to be checked if the NN search is already working.

**Comment by christianfrei** [comment]
Tags are sent via query, looks like all is working.

@silvanheller can you test it please because i have no trained videos

**Comment by silvanheller** [comment]
Waiting for Cineast with the new GRPC-File

**Comment by silvanheller** [comment]
Waiting for Cineast with the new GRPC-File https://github.com/silvanheller/cineast/pull/55

**Comment by silvanheller** [comment]
Working
