### ISSUE TITLE
Seperate between Multi-Shot Selection and Single-Shot Selection

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/vitrivr-ui#20]
They are different types and have different options.

**Comment by christianfrei** [comment]
implemented in a7bcb098c3da0ec23fdb17557257973565fbae8e

needs possible refactoring as soon as the API supports the new feature (therefore will not close this issue)

**Comment by christianfrei** [comment]
first try in bd23318195d7f4512e21093136003b5b2555f196 if it's working since API supports now MultipleSegments

**Comment by christianfrei** [comment]
works now

Enhancement: At mimimum 2 shots should be selected before request can be sent (with 1 shot it doesn't make sense)

**Comment by christianfrei** [comment]
implemented in 908fd7aaebdec666426c2314c1c3268176ea07d2
