### ISSUE TITLE
Shot Selection over multiple Movies not working

### ISSUE THREAD

**Issue by christianfrei** [silvanheller/vitrivr-ui#22]
needs further bug fix

**Comment by silvanheller** [comment]
Can you provide a console output of the UI / cineast/ the ADAMpro-container?

**Comment by christianfrei** [comment]
I am currently working on this. I found the bug so the array was filled with the same IDs again and again. Because we can now add shots from different movies, I will refactor the whole shot selection.

**Comment by christianfrei** [comment]
fixed in 575a53c214d20b0c4b0e1507ef9f3349f9f663d5
