### ISSUE TITLE
Perform getLabels - API Call

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/vitrivr-ui#7]
The API returns Mock Labels and i will provide a dockercontainer with labels & extracted data soon. It would be optimal if the UI would retrieve available labels when the object-button :sunglasses: is clicked

**Comment by christianfrei** [comment]
The prototype of this is implemented, will be tested tomorrow. For testing purposes the labels are loaded at the page loading and not by click on :sunglasses:. But this will be changed after testing.

**Comment by silvanheller** [comment]
Done
