### ISSUE TITLE
Enter adds label

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/vitrivr-ui#8]
When hitting enter, the label that is currently in the textbox is ideally added to tags

**Comment by christianfrei** [comment]
You can enter one/several letter(s) and some tags are displayed by auto completion. If you hit "enter" the first suggested tag is entered to the input field and if you hit "enter" again it is send to the tags.

If you enter a letter/expression which is not available nothing will happen if you press enter.

Added this enhancement in 0dfd894b5a485a098762a94e600f9f6f69d0dd75
